jwt:
  secret: 1A50EF4F7AB1F6069BC04EEABFA52D66257D47E7FBBE0D7C1C20D2D88E9489C5
  issuer: http://localhost:8501
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ums-test
    username: ums
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8501
