jwt:
  secret: 1A50EF4F7AB1F6069BC04EEABFA52D66257D47E7FBBE0D7C1C20D2D88E9489C5
  issuer: http://localhost:4200
  expiration: 300000 # 5 min
  refresh-expiration: 86400000 # 1 day
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ums-db
    username: ums
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migrations
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    baseline-version: 1
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8501
